### ISSUE TITLE
the index in deepfashion

### ISSUE THREAD

**Issue by eternaldolphin** [cuiaiyu/street-tryon-benchmark#3]
how can i know which models are wearing the same dress.
or do u have the image index in deepfashion so that i can get the above information

**Comment by cuiaiyu** [comment]
Thanks for your interest! 

- The data source is [deepfashion2](https://github.com/switchablenorms/DeepFashion2/tree/master) instead of [deepfashion](https://mmlab.ie.cuhk.edu.hk/projects/DeepFashion.html).

- The `pair_id` in [the original deepfashion2 annotations](https://github.com/switchablenorms/DeepFashion2?tab=readme-ov-file#data-organization) should provide you with some information regarding which images are paired (sharing the same garment source).  To find this information, please use the image_name `xxxxxx.jpg` (provided in our selected image list) to trace the associated `.json` file from the original deepfashion2 annotation. In the `.json` file, you can find more deepfashion2 annotations.

- However, due to the deepfashion2 dataset nature, these `pair_ids` may have ambiguity as it sometimes labels two garments in different colors (but the same otherwise) with the identical `pair_id.` In addition, after filtering (removing images that are not feasible for try-on tasks,) only a small number of pairs are left. For this reason, we consider this dataset an `unpaired` try-on benchmark.

**Comment by eternaldolphin** [comment]
do you know the passwd of deepfashion2? 
i can not unzip the data with the email given by filling the google form
